trigger: none

stages:
  - stage: CI_Build
    displayName: CI - Build
    jobs:
      - job: Build_App
        displayName: Build Application
        steps:
          - script: mvn test
            displayName: Unit Tests
          - task: PublishTestResults@2
            displayName: "Publish test results"
            inputs:
              testResultsFormat: "JUnit"
              mergeTestResults: true # Optional
          - task: PublishCodeCoverageResults@1
            displayName: "Publish publish code coverage"
            inputs:
              summaryFileLocation: $(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml
              pathToSources: $(System.DefaultWorkingDirectory)/src/main/java/
          - script: mvn package
          - publish: "target/helloworld.war"
            artifact: build_artifacts